# Generated by Django 4.2.6 on 2024-04-24 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='birthday',
        ),
    ]
