# Generated by Django 4.2.6 on 2024-04-23 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Estudiante', '0002_initial'),
        ('Requisito', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='requisitos_cumplidos',
            field=models.ManyToManyField(blank=True, related_name='estudiantes_cumplidos', to='Requisito.requisito'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='requisitos_cumplidos_permanecer',
            field=models.ManyToManyField(related_name='estudiantes_cumplieron_permanecer', to='Requisito.requisito'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='requisitos_cumplidos_subir',
            field=models.ManyToManyField(related_name='estudiantes_cumplieron_subir', to='Requisito.requisito'),
        ),
    ]
