# Generated by Django 4.2.6 on 2024-04-23 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Nivel', '0001_initial'),
        ('Requisito', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nivel',
            name='coordinador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nivel',
            name='requisitos',
            field=models.ManyToManyField(to='Requisito.requisito'),
        ),
    ]
