# Generated by Django 4.2.6 on 2024-04-24 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Requisito', '0001_initial'),
        ('Nivel', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nivel',
            name='coordinador',
        ),
        migrations.AlterField(
            model_name='nivel',
            name='requisitos',
            field=models.ManyToManyField(blank=True, related_name='requisitos_nivel', to='Requisito.requisito'),
        ),
    ]
