# Generated by Django 5.0.6 on 2024-06-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nivel', '0003_remove_nivel_coordinador_alter_nivel_requisitos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nivel',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
