# Generated by Django 5.0.6 on 2024-06-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nivel', '0004_alter_nivel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nivel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
